[package]
org = "ballerina"
name = "log"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["level", "format"]
repository = "https://github.com/ballerina-platform/module-ballerina-log"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
path = "../native/build/libs/log-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/log-test-utils-@project.version@.jar"
