[package]
org = "ballerina"
name = "log"
version = "2.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/log-native-2.0.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/log-test-utils-2.0.0-SNAPSHOT.jar"
