[package]
org = "ballerina"
name = "integration_tests"
version = "2.4.0"
[[platform.java11.dependency]]
path = "../native/build/libs/log-native-2.4.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/log-test-utils-2.4.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/io-native-1.3.0-20220718-152300-9eb8217.jar"
