[package]
org = "ballerina"
name = "integration_tests"
version = "@toml.version@"

[[platform.java17.dependency]]
path = "../native/build/libs/log-native-@project.version@.jar"

[[platform.java17.dependency]]
path = "../test-utils/build/libs/log-test-utils-@project.version@.jar"

[[platform.java17.dependency]]
path = "./lib/io-native-@io.native.version@.jar"
