[package]
org = "ballerina"
name = "integration_tests"
version = "2.2.0"
[[platform.java11.dependency]]
path = "../native/build/libs/log-native-2.2.0.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/log-test-utils-2.2.0.jar"

[[platform.java11.dependency]]
path = "./lib/io-native-1.2.0.jar"
