[package]
org = "ballerina"
name = "integration_tests"
version = "2.8.0"
[[platform.java11.dependency]]
path = "../native/build/libs/log-native-2.8.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/log-test-utils-2.8.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/io-native-1.5.0-20230614-150600-6387868.jar"
