[package]
org = "ballerina"
name = "integration_tests"
version = "2.1.0"
[[platform.java11.dependency]]
path = "../native/build/libs/log-native-2.1.0.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/log-test-utils-2.1.0.jar"

[[platform.java11.dependency]]
path = "./lib/io-native-1.1.0.jar"
