[package]
org = "ballerina"
name = "integration_tests"
version = "2.9.0"
[[platform.java17.dependency]]
path = "../native/build/libs/log-native-2.9.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
path = "../test-utils/build/libs/log-test-utils-2.9.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
path = "./lib/io-native-1.6.0-20230810-115500-2e569f5.jar"
